name: Check the tapplet

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Tapplet package name"
        required: true
        default: "tapp-example"
      package-version:
        description: "The tapplet package version"
        required: true
        default: "1.0.0"

  pull_request:
    branches:
      - main

# Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
permissions:
  contents: write

jobs:
  get-tapp-id:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.var-setup.outputs.name }}
      version: ${{ steps.var-setup.outputs.version }}
      param: ${{ steps.var-setup.outputs.param }}
    steps:
      - name: Variables setup
        id: var-setup
        shell: bash
        run: |
          pr_name=${{ github.event.pull_request.title }}
          IFS="@" read -r NAME VERSION_PARAM <<< "$pr_name"
          IFS="-" read -r VERSION PARAM <<< "$VERSION_PARAM"
          echo "Name: $NAME"
          echo "Version: $VERSION"
          echo "Param: $PARAM"
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version=${PARAM}" >> $GITHUB_OUTPUT

  check-tapp:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.tapp-checker.outputs.status}}
    needs: get-tapp-id

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check tapplet package
        id: tapp-checker
        uses: karczuRF/ga-test@main
        with:
          package-name: ${{needs.get-tapp-id.outputs.name}}
          package-version: ${{needs.get-tapp-id.outputs.version}}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
