name: Check the tapplet

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Tapplet package name"
        required: true
        default: "tapp-example"
      package-version:
        description: "The tapplet package version"
        required: true
        default: "1.0.0"

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  read-variables:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.var-setup.outputs.name }}
      version: ${{ steps.var-setup.outputs.version }}
    steps:
      - name: Variables setup
        id: var-setup
        shell: bash
        run: |
          pr_name=${{ github.event.pull_request.title }}
          IFS="@" read -r NAME VERSION <<< "$pr_name"
          echo "Name: $NAME"
          echo "Version: $VERSION"
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  check-tapp:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.tapp-register.outputs.status}}
    needs: read-variables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register tapplet
        id: tapp-register
        uses: karczuRF/ga-test@main
        with:
          package-name: ${{needs.read-variables.outputs.name}}
          package-version: ${{needs.read-variables.outputs.version}}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-registry:
    runs-on: ubuntu-latest
    needs: check-tapp

    steps:
      - name: Commit updated files
        id: push-commit
        run: |
          if [ ${{ needs.check-tapp.outputs.status }} ]; then
            git config user.name "karczuRF"
            git config user.email "${{ secrets.EMAIL }}"
            git add -A
            git commit -m "Register tapplet"
            git fetch origin
            git rebase --strategy-option=theirs origin/main
            git push origin HEAD:${{github.ref_name}} --force
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
