name: Create Pull Request

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
