name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Tapplet package name"
        required: false
        default: "tapplet-example"
      manifestVersion:
        description: version
        default: "1.0.0"
        required: false

  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register tapplet
        uses: karczuRF/ga-test@main
        with:
          package-name: ${{ github.event.inputs.package-name }}
          manifest-version: ${{ github.event.inputs.manifest-ersion }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
