name: Check the tapplet

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Tapplet package name"
        required: true
        default: "tapp-example"

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register tapplet
        uses: karczuRF/ga-test@main
        with:
          package-name: tapp-example

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO
      - name: Commit manifest
        id: push-commit
        run: |
          git config user.name "karczuRF"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          git commit -m "Register tapplet"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push origin HEAD:tapp/tapp-example-1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
