name: Create Pull Request

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register tapplet
        uses: karczuRF/ga-test@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
