name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Tapplet package name"
        required: false
        default: "tapplet-example"
      manifest-version:
        description: version
        default: "1.0.0"
        required: false
      dir:
        description: "Optional subfolder directory to save the json file. | src/ "
        required: false

  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Register tapplet
        uses: karczuRF/ga-test@main
        with:
          package-name: tapp-example
          manifest-version: 1.0.3
          dir: ${{ github.workspace }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit manifest
        id: push-commit
        run: |
          git config user.name "karczuRF"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          git commit -m "Register tapplet"
          git merge --no-ff origin HEAD:feat/tapp-example
          git push origin HEAD:feat/tapp-example

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
